import { describe, it, expect } from 'vitest';
import { readFileSync, readdirSync } from 'node:fs';

// ═══════════════════════════════════════════════════════════════════════════
// RONDA 7 · "¿ESTÁ COMPROBADA LA 00XX?" NO PODÍA CONTESTARSE.
//
// `supabase/verificaciones.sql` prueba lo que solo la base puede demostrar:
// índices únicos, claims atómicos, permisos. Es el único sitio del repo donde se
// comprueban garantías que un test con Supabase mockeado no toca —ese prueba el
// mock—. Y no había forma de saber qué migraciones cubría: la respuesta era
// abrir el archivo y contar.
//
// Así se coló la 0030, que es la migración MÁS irónica para colarse: existe
// exactamente porque un chequeo de arranque decía verificar la 0019 y no podía.
// La migración escrita para que un chequeo dejara de mentir se quedó, ella
// misma, sin comprobar.
//
// Al escribir esta lista aparecieron otras TRES —la 0002, la 0011 y la 0012—,
// que es para lo que sirve escribirla. Ahora son los bloques 14, 15 y 16.
//
// Esta prueba no lee SQL ni valida sintaxis. Hace UNA sola cosa: obliga a que
// toda migración nueva tome una decisión explícita —bloque o exención con
// razón— en vez de dejarla al olvido, que es el default de hoy.
// ═══════════════════════════════════════════════════════════════════════════

const DIR = 'supabase/migrations';

/**
 * Los TÍTULOS de los bloques, no el archivo entero.
 *
 * Buscar el número en todo el SQL daba falsos verdes: un bloque puede nombrar
 * media docena de migraciones en su prosa para explicar el contexto —el 14 cita
 * la 0011 y la 0005— sin comprobar ninguna de ellas. El título es donde el autor
 * del bloque DECLARA qué está comprobando, y es lo único que se puede leer como
 * una afirmación.
 *
 * Formato: `-- ── 14. El contador de la barrera (mig. 0011 + 0031) ──────`
 */
const TITULOS = readFileSync('supabase/verificaciones.sql', 'utf8')
  .split('\n')
  .filter((l) => /^-- ── \d+\./.test(l))
  .join('\n');

/**
 * Migraciones que NO necesitan bloque, con la razón de cada una.
 *
 * El criterio: hace falta bloque cuando la migración crea una garantía que la
 * base es la ÚNICA que puede demostrar —unicidad, atomicidad, permisos—. Una
 * columna nueva, un bucket o un índice de velocidad no entran: si faltan, algo
 * revienta ruidosamente o va lento, no se corrompe en silencio.
 */
const EXENTAS: Record<string, string> = {
  '0324': 'GPS durable/justo: sus contratos de catálogo, aislamiento y carreras de dos sesiones viven en supabase/tests/0324_gps_poll_durable.sql, 0324_gps_ronda2_red.sql y 0324_gps_concurrencia.sh, ejecutados contra PostgreSQL real; no se duplica esa prueba especializada en verificaciones.sql.',
  '0325': 'Capacidad WA/jornada: el orden causal, sincronización y carrera real se prueban en supabase/tests/0325_capacidad_wa_jornada.sql, 0325_jornada_concurrencia.sh y 0325_upgrade_forward_only.sh; son contratos multi-sesión/set-based que la compuerta genérica no puede representar.',
  '0327': 'Reaplica forward-only el contrato Cal.com de 0323 y su retención; supabase/tests/0327_calcom_retencion_forward.sql prueba forma, permisos y comportamiento contra PostgreSQL real. La cobertura especializada evita declarar un segundo baseline en verificaciones.sql.',
  '0328': 'Entrega GPS/Meta queda supersedida y endurecida por 0330/0333; las suites supabase/tests/0330_gps_r3_red.sql, 0330_gps_r3_concurrencia.sh y 0333_gps_r4_red.sql ejercen el contrato vigente, incluida la carrera, sobre PostgreSQL real.',
  '0329': 'Capacidad ronda 2 tiene pruebas especializadas de deadlock y carga set-based en supabase/tests/0329_shared_unit_no_deadlock.sh y 0329_gps_setbased_load.sh, además de las regresiones 0327; son garantías de concurrencia que no caben en un bloque aislado de verificaciones.sql.',
  '0330': 'GPS receipts ronda 3 se prueba en supabase/tests/0330_gps_r3_red.sql y 0330_gps_r3_concurrencia.sh contra PostgreSQL real, incluidos orden, reconciliación y dos sesiones; esa es evidencia más fuerte que duplicar presencia estática.',
  '0331': 'Capacidad ronda 3 se prueba en supabase/tests/0331_capacidad_r3_red.sql y las suites de concurrencia/upgrade 0325–0329; fija versión canónica y orden global de locks en PostgreSQL real.',
  '0333': 'GPS ronda 4 tiene arneses especializados de contrato SQL y carrera real en supabase/tests/0333_gps_r4_red.sql y 0333_gps_r4_concurrencia.sh. Esta exención sólo clasifica dónde vive la evidencia; no afirma que ci-postgres los ejecute.',
  '0334': 'Capacidad ronda 4 tiene arneses especializados en supabase/tests/0334_capacidad_r4_red.sql y 0334_capacidad_r4_concurrencia.sh para atomicidad, PK inmutable y ambigüedad unidad/día. Esta exención no afirma integración en ci-postgres.',
  '0335': 'Retención DB R3 se prueba en supabase/tests/0335_db_retencion_r3_red.sql y 0335_db_retencion_r3_concurrencia.sh, integrados al job ci-postgres: error 0104, deadline por filas, definición exacta de índices y carrera escritor/snapshot. El preflight concurrente se verifica antes de 0332, fuera de la transacción.',
  '0336': 'Capacidad ronda 5 tiene arneses especializados en supabase/tests/0336_capacidad_r5_red.sql, 0336_capacidad_r5_concurrencia.sh y 0336_capacidad_r5_load.sh: día operativo actual y DST, transiciones INSERT/UPDATE/DELETE, GPS/unidad compartida, carrera de dos sesiones y cardinalidad 5k/50k sobre PostgreSQL real. Esta exención clasifica la evidencia; no afirma integración en ci-postgres.',
  '0337': 'GPS ronda 5 tiene arneses especializados en supabase/tests/0337_gps_r5_red.sql y 0337_gps_r5_concurrencia.sh: lote atómico de 2,000 acuses, dedupe determinista, rollback total, T2 monótono y overfetch acotado bajo 300/400 advisory locks sobre PostgreSQL real. Esta exención clasifica la evidencia; no afirma integración en ci-postgres.',
  '0338': 'Retención DB R5 elimina el lock y GROUP BY diarios de producto_evento y reemplaza el lock mensual de tabla por un gate asesor compartido/exclusivo que no compite con autovacuum; supabase/tests/0338_db_retencion_r5_red.sql y 0338_db_retencion_r5_concurrencia.sh, integrados al mismo job ci-postgres, fijan reloj, permisos del gate, writer abierto y rollover exacto con 50,000 eventos. Las suites 0330/0335 siguen fijando fallback, watermark y carrera escritor/snapshot.',
  '0339': 'Integridad de la cola y ACL de triggers se comprueban en supabase/tests/0339_jornada_integridad_red.sql, ejecutado en el job ci-postgres existente: service_role rechaza operador/viaje de otro tenant, acepta el propio, conserva cascada y anon/authenticated no pueden ejecutar los cuatro triggers. La batería global conserva sus barridos de FK compuestas y SECURITY DEFINER.',
  '0340': 'Sólo corrige el texto predeterminado y COMMENT de cancelación ARCO, conservando definición, permisos y datos históricos. supabase/tests/0340_arco_alcance.sql ejecuta RPC real, verifica alcance, retención/supresión, aislamiento y ACL; integrado en ci-postgres.',
  '0341': 'supabase/tests/0341_gps_alerta_minima.sql demuestra forma mínima sin PII adicional, FK SET NULL sin pérdida del evento, huérfanos/legacy fuera del drenado, tenant/proveedor/leases, dedupe y entrega sólo con receipt. 0341_gps_alerta_minima_concurrencia.sh demuestra claims SKIP LOCKED sin solape en dos sesiones; ambas corren en ci-postgres.',
  '0316': 'RE-AUDITORÍA 25, FIS-REAUD-1 (CRÍTICO): redefine `gastos_fiscales_agregados_tenant` (misma firma que la 0151/0192) agregando un `left join liquidacion` que expone `liquidacionFirmada` por celda — mismo molde que la 0190/0305/0308 (redefine una agregación existente cambiando/agregando SOLO un criterio, sin unicidad/atomicidad/permiso nuevo). El bloque 123 de verificaciones.sql (0151) y el 229 (0282) siguen probando el catálogo/aislamiento/equivalencia de la MISMA función contra Postgres real — se actualizaron para la firma nueva (ver la mig. 0317, que la vuelve a extender) sin que cambie ninguna de sus aserciones: el join es LEFT, así que no filtra ni una fila de las que esos bloques ya cuentan. Que `ivaSostenible` (fiscal.ts) niegue el acreditamiento cuando `liquidacionFirmada` es falso, y que el resto del panel (gastoTotal/perdidas) NO se filtre por esto, lo fija `fiscal.test.ts` (describe FIS-REAUD-1) y la equivalencia JS-vs-RPC de `fiscal_agregado.test.ts`.',
  '0317': 'RE-AUDITORÍA 25, FIS-REAUD-2 (CRÍTICO): extiende la MISMA redefinición de `gastos_fiscales_agregados_tenant` que la 0316 (necesita DROP porque la firma gana 6 parámetros — ver la cabecera de la migración) agregando 6 dimensiones más (rfcReceptor, monedaExtranjera, renglonesAjenos, consumoBar, complementoHidrocarburosFalta, otroEjercicio), cada una una fórmula mecánica fila-por-fila con sus parámetros mandados desde TS — el MISMO patrón que `sobreTopeEfectivo` ya usaba desde la 0151. Sin unicidad/atomicidad/permiso nuevo que la base sea la única en demostrar: SQL sigue sin juzgar deducibilidad, solo agrupa. Los bloques 123/229 de verificaciones.sql se actualizaron a la firma de 13 parámetros con valores que no disparan ninguna de las 6 causas nuevas (mismo resultado que antes de esta migración para lo que esos bloques miden) — la corrección DE LAS FÓRMULAS (el patrón de bar traducido a `\\y`, el umbral de renglones ajenos, la fecha de otro ejercicio, el veredicto duro del complemento de hidrocarburos) la fija la equivalencia JS-vs-RPC de `fiscal_agregado.test.ts` (que reimplementa cada fórmula de forma independiente y las compara contra el resultado agregado) y las 9 pruebas dedicadas de `fiscal.test.ts` (describe FIS-REAUD-2) que prueban cada causa contra `ivaSostenible` directo, con rojo/verde comprobado contra la implementación real.',
  '0308': 'redefine `acreditables_liquidacion_tenant` (misma firma que la 0112) agregando SOLO `and revision in (\'aprobada\', \'ajustada\')` al WHERE — mismo molde que la 0190 (redefine sumar_combustible_ejercicio cambiando solo qué cuenta). No crea unicidad/atomicidad/permiso nuevo: es la MISMA agregación de la 0112, con un filtro adicional. Auditoría 25, ALTO fiscal (fiscal.md línea 145) — antes sumaba también liquidaciones `rechazada` y `pendiente`. Que la RPC excluya esas dos y siga sumando `aprobada`/`ajustada` lo fija `analytics_kpis_acreditables.test.ts` (equivalencia JS-vs-RPC con las cuatro revisiones, incluido el escenario del hallazgo: el viaje 4471 rechazado con $16,000 de IVA que ya no aparecen).',
  '0313': 'columna incidencia.avisada_jefe_en (timestamptz, nullable) — mismo patrón que 0087/0080: un dato aditivo, sin unicidad/atomicidad/permisos que solo la base pueda demostrar. Si falta, el SELECT de talacha_wa.ts (pendienteDelViaje) falla ruidoso — PostgREST rechaza la columna inexistente, no la trata como NULL. El comportamiento que la columna habilita (agentico.md:455: no reafirmar "tu jefe ya tiene la solicitud" sin haberlo comprobado) se prueba en TS contra el mock de Supabase (talacha_wa.test.ts, describe "el aviso al jefe que falló se reintenta").',
  '0301': 'marcaba los nueve agentes teatro como experimental=true; su bloque (antes 248) se retiró el 2-sep-2026 al graduarlos la 0303 — mismo criterio que la 0038/0041 (una migración posterior revierte por completo lo que ésta hizo, así que el bloque que lo comprobaba pasaría en verde probando algo que ya no es cierto). La garantía que reemplaza a "los nueve quedan experimental=true" es su opuesta exacta, "los nueve quedan experimental=false", y la prueba el bloque 249 (0303) — que también absorbió el sub-check del default de columna que el 248 traía (letra e), para no perder esa cobertura al retirar el bloque.',
  '0302': 'DROP FUNCTION del overload huérfano de 6 argumentos de reservar_presupuesto_llm (creado en 0186/0193, sustituido por el de 8 argumentos de la 0244, que nunca lo retiró). No crea garantía nueva de unicidad/atomicidad/permisos: retira superficie muerta. La 0244 nunca tuvo bloque propio con ese mismo criterio, y el único call-site real (src/lib/llm/budget.ts) ya llama la firma de 8 argumentos con parámetros nombrados — confirmado por grep exhaustivo de src/ antes de escribir el DROP. Si algún caller olvidado dependiera del overload de 6, el error de PostgREST (función no encontrada) es ruidoso, no corrupción silenciosa.',
  '0300': 'reconcilia dos redefiniciones independientes de gasto_no_tras_liquidar() (0283 fiscal + 0299 revision, que se pisaron sin saberlo — ver la cabecera de la 0300). No crea una garantía nueva: es la MISMA garantía que la 0283 ya declaraba, que el bloque 230 (INMUTABLE_TRAS_LIQUIDAR_0283) sigue probando — verificado en rojo contra la función pisada por la 0299 (mover/reten/descuento en falso) y en verde tras aplicar la 0300, contra Postgres real con las 279 migraciones en orden.',
  '0183': 'elimina dos índices físicamente duplicados señalados por los advisors de producción; no crea una garantía nueva. La existencia/forma del índice GPS conservado ya la prueba el bloque 147 y el drenado de WhatsApp se prueba en TS y en el claim del bloque 148.',
  '0184': 'fija search_path y revoca RPC de una función trigger SECURITY INVOKER. El advisor de Supabase comprueba directamente la ausencia del hallazgo; el trigger sigue probado por el bloque 139 de la 0167.',
  '0247': 'fija el search_path de qa_verdad_terreno_valida — mismo caso que la 0184, y con una comprobación MÁS fuerte que la de aquélla: no se apoya en el advisor de Supabase (que solo mira después de aplicar a producción), sino en el bloque E de supabase/pruebas-aislamiento/capa1_auditoria_estatica.sql, que el mismo runner de CI corre sobre base virgen y que barre TODAS las funciones de public por catálogo, no por lista de nombres. No va en verificaciones.sql porque no hay una garantía puntual de esta migración que probar: lo que se prueba es la propiedad general de que ninguna función nuestra se quede sin search_path, presente o futura. La lógica de la función no se toca (alter function … set, no create or replace) y su regla de las dos listas la sigue comprobando el CHECK de qa_foto que la 0239 le cableó.',
  '0261': 'cambia el default de wa_evento_pendiente.recibido_en de now() a clock_timestamp() (BE-C1): dentro de un INSERT multi-fila now() empata en las N filas de la misma transacción y el desempate (recibido_en, id) caía en el wamid, que no es cronológico. La garantía real —que el desempate SÍ sea cronológico dentro de una ráfaga— la comprueba supabase/tests/wa_leases_fencing.sql en pgTAP contra Postgres real (Capa 0 de ci-postgres.yml), no un bloque de verificaciones.sql: el bug es de semántica de transacción (now() vs clock_timestamp()) y un bloque de verificaciones.sql —que corre cada statement en su propia transacción vía el runner— no puede reproducir el empate multi-fila que solo aparece dentro de UN mismo INSERT. Verificado rojo/verde: 5/40 aserciones fallan con now(), 40/40 pasan con clock_timestamp().',
  '0264': 'extiende el search_path de ejecutar_arco_cancelacion a `public, extensions, pg_catalog` (0173/0178), sin calificar las llamadas a digest(): sin `extensions` en el search_path, la llamada truena SIEMPRE con "function digest(text, unknown) does not exist" en Supabase gestionado, donde pgcrypto vive en el esquema `extensions` — defecto heredado desde la 0173, nunca ejercido en producción (0 cancelaciones ARCO reales intentadas). El bloque 210 de verificaciones.sql YA prueba esta función end-to-end (llama ejecutar_arco_cancelacion de verdad y espera ok=t), y sigue siendo la prueba correcta después de este cambio — pero corre sobre el Postgres LOCAL de CI, donde `andamio_ci.sql` instala pgcrypto en `public`, así que digest() sin calificar YA resolvía ahí antes del fix; por eso el bloque pasaba en verde en CI mientras la función fallaba en producción. Verificado en vivo: la llamada real contra producción truena antes del fix y completa después, con rfc/licencia en NULL. Se descartó calificar la llamada como `extensions.digest`: medido contra el Postgres LOCAL de CI, ese esquema no tiene la extensión instalada ahí (vive en `public` localmente), así que habría arreglado producción rompiendo CI — extender el search_path (en vez de quitar `public`) resuelve en los dos entornos, cada uno por el esquema donde de hecho tiene la extensión. Pendiente, fuera de esta migración: alinear `andamio_ci.sql` para instalar pgcrypto en `extensions` como Supabase gestionado, para que esta familia de bug (mismatch de layout de esquemas local/gestionado) se atrape en CI la próxima vez — es la misma brecha que ya encontró el fork de Playwright con los GRANT de `supabase start`.',
  '0275': 'restaura con `alter function ... set search_path` el `extensions` que la 0264 había agregado a ejecutar_arco_cancelacion y que la 0273 revirtió al partir del cuerpo de la 0262 (la versión ANTERIOR al arreglo). Mismo caso que la 0184 y la 0247: toca la cabecera de la función, no su cuerpo, y no crea ninguna garantía nueva de unicidad, atomicidad ni permisos que solo la base pueda demostrar. No lleva bloque en verificaciones.sql POR DISEÑO, y ésa es la lección de este hallazgo: el bloque 210 YA llama ejecutar_arco_cancelacion de verdad y espera ok=t, y pasó en VERDE los dos días que el defecto estuvo puesto, porque corre sobre el Postgres LOCAL de CI, donde andamio_ci.sql deja que la 0001 instale pgcrypto en `public` y digest() sin calificar resuelve igual. El bloque E de capa1_auditoria_estatica.sql tampoco lo ve: comprueba que exista *algún* search_path=, nunca su contenido. Un bloque más en verificaciones.sql habría vuelto a pasar en verde. La red que sí atrapa esta familia es estática y vive en TS: src/lib/likida/arco_search_path.test.ts lee la ÚLTIMA definición vigente de la función en supabase/migrations/ y exige `extensions` en su search_path mientras el cuerpo llame a digest() sin calificar — anclada a «la última», no a la 0273, así que la próxima migración que redefina la función partiendo de un cuerpo viejo cae ahí igual.',
  '0269': 'RPC de lectura ultimas_posiciones_tenant (distinct on por unidad sobre `posicion`) — mismo molde que la 0084/0112/0162: si la función falta, `getUltimasPosiciones` LANZA ruidoso en el primer render de /dashboard/mapa (el RPC no existe) y la página pinta su error de lectura en vez de un mapa sin pines. No crea garantía de unicidad, atomicidad ni permisos que solo la base pueda demostrar: es un SELECT stable, sin escrituras, con el mismo grant a service_role que sus hermanas. El contrato en TS (forma de cada fila, fail-closed ante otra forma, aislamiento por tenant del argumento) se prueba en comercial_rastreo.test.ts.',
  '0137': 'columna prospecto.unidades + check > 0. No crea garantía que solo la base pueda demostrar: si la columna falta, /api/lead lo detecta por el mensaje del insert y salva el lead en `notas` (probado en api/lead/route.test.ts, "la red de seguridad de la 0137"). El check de positivos es la misma forma que plan_limites_positivos, que tampoco tiene bloque: un valor inválido rebota ruidoso en el INSERT, no se corrompe en silencio.',

  '0112': 'RPCs de agregados en SQL (serie_comparativa_tenant + redefine sumar_combustible_ejercicio, patrón 0084): si faltan, getSerieComparativa/getAcumuladoCombustible LANZAN ruidoso (el RPC no existe — fail-closed explícito con aviso de lasi pasada, el mismo criterio de la 0084). El contrato de la serie en TS se prueba en analytics_serie_comparativa.test.ts (mapeo, null de costo, forma `pasos` periodos); la corrección LOCAL-MX del bucketeo ahora la garantiza la función SQL, que a su vez es runtime-ruidoso si falla, y queda cubierta por el bloque 21 (0022/log?) del propio flujo documentado en la migración. Sin garantía de unicidad/atomicidad/permisos que la base sea la única que pueda demostrar.',

  '0087': 'columna viaje.recordatorio_comprobacion_en + índice parcial — el mismo patrón que escalado_en (0058, sin bloque propio: su claim tampoco se verifica ahí, el bloque 37 de esa migración prueba otra cosa). La garantía real es que el UPDATE condicional (WHERE recordatorio_comprobacion_en IS NULL, la misma columna que escribe) es atómico por construcción de Postgres — no una regla de negocio que este repo agregue, sino la semántica estándar de un UPDATE con WHERE. El claim anti-doble-envío vive desde la 0089 en el INSERT con unique(viaje, tier) de cobranza_contacto (bloque 64 la verifica con corrida real), y la lógica de tiers y del sello se prueba en TS (agentes/cobranza.test.ts) — recordatorio_comprobacion.ts y sus 15 pruebas se borraron el 14-ago-2026 al quedar supersedidos por ese agente.',
  '0080': 'columna operador.rfc: dato opcional capturado por la flota. La rama buena de RLISR 57 se prueba en TS (engine/desde_db); si la columna falta, getOperador falla ruidoso.',
  '0082': 'redefine config_tenant_valida con la llave facilidadCombustibleEfectivo: si falta, el alta de flota que declare su régimen revienta con el error del 0026 (ruidoso, no silencioso).',
  '0083': 'redefine config_tenant_valida exigiendo la FORMA de la facilidad: si falta, una config con "sí" en la llave revienta ruidoso en el UPDATE del tenant.',
  '0084': 'RPC sumar_combustible_ejercicio: si falta, getAcumuladoCombustible lanza ruidoso en el primer cuadre (el RPC no existe). El resultado se prueba en TS contra el esquema de migraciones.',
  '0085': 'redefine config_tenant_valida: la 0083 asignaba jsonb a una variable record (crash "anonymous composite types") en cada UPDATE de tenant con la facilidad declarada. El bloque 61 de verificaciones.sql reproduce el escenario exacto (update con facilidad en config).',
  // ── Prospecto / scoring de ventas (pipeline de Likida, NO dinero de flota) ──
  // Mismo criterio que 0137: columnas aditivas y ajustes de un SCORE de ventas.
  // No crean una garantía que solo la base pueda demostrar (unicidad/atomicidad/
  // permisos): si una columna falta, el código que la lee falla ruidoso; si el
  // cálculo del score cambia, es lógica de negocio del embudo, probada en TS, y
  // un score mal solo mueve el ORDEN de la lista de prospectos —nunca una cifra
  // fiscal ni un cobro—. Ninguna toca `gasto`/`liquidacion`/`viaje`/`suscripcion`.
  '0140': 'columnas de investigación profunda + score de filtrado en `prospecto`. Aditivas; su ausencia rompe ruidoso la escritura del censo, no corrompe en silencio. El score es orden de ventas, no dinero.',
  '0141': 'columna `mensaje_linkedin` en `prospecto` (el tercer toque). Aditiva, sin garantía que la base sea la única en demostrar — misma forma que 0129.',
  '0142': 'ajuste del cálculo de `necesidad_pct` (excluye "auxiliar administrativo" suelto). Es un SCORE de prospección; su corrección es lógica de negocio del embudo, no un invariante de dinero. Un valor mal reordena la lista, no corrompe.',
  '0143': 'ajuste del cálculo de `necesidad_pct` (excluye "liquidación de pagos", que no es "liquidación de viajes"). Mismo criterio que 0142: score de ventas, no dinero.',
  '0001': 'esquema base: si falta, no arranca nada. Un bloque no aporta información que el primer INSERT no dé.',
  '0003': 'tabla de costos de LLM: telemetría. No hay garantía que romper.',
  '0004': 'columna de config fiscal. El bloque 7 (0026) sí comprueba lo que importa: que esa config no pueda apagar un tope de dinero.',
  '0006': 'columnas del complemento de hidrocarburos. Su corrección se prueba en TS contra el XML.',
  '0007': 'columnas de acreditamiento (IVA/IEPS). Los números los prueba el motor, que es puro.',
  '0008': 'bucket de storage. Si falta, la subida falla con un error visible.',
  '0009': 'columnas de XML crudo y EFOS. La retención de CFF 30 se prueba en TS; aquí solo hay dónde guardarlo.',
  '0010': 'columna ocr_extra. El claim que la protege es la 0017, bloque 3.',
  '0014': 'columna img_hash. Su unicidad la ponen la 0015 y la 0027.',
  '0015': 'su índice `uq_gasto_img_hash` lo DROPEA y recrea la 0027, que sí tiene bloque (8). Comprobar el de la 0015 sería comprobar un índice que ya no existe.',
  '0016': 'tabla `codigo_pendiente`. El arranque la sondea leyéndola y su ausencia da error de PostgREST, no corrupción.',
  '0018': 'columnas del aviso de privacidad. Su claim atómico es `marcar_aviso_privacidad`, que sí tiene prueba en TS con el RPC real mockeado — y la constancia falsa, que es el riesgo, se prueba en `aviso_constancia.test.ts`.',
  '0020': 'columna `demora_no_imputable`. El que se leyera o no es un bug de SELECT, ya cerrado y probado en TS.',
  '0021': 'litros de diésel en la liquidación. La firma ambigua que dejó es lo peligroso, y ESO es el bloque 5 (0022).',
  '0023': 'índice de velocidad para el acumulado del ejercicio. Sin él la consulta va lenta; no cambia ningún número.',
  '0034': 'columna nullable `tenant.contacto_privacidad` (art. 29). Si falta, el aviso integral marca esa sección como pendiente — que es su comportamiento con la columna vacía, así que no hay garantía que la base pueda romper. El contenido se prueba en `aviso_integral.test.ts`.',
  '0035': 'solo `alter function ... set search_path`, y las diez son SECURITY INVOKER: no hay escalada que comprobar. Lo que sí se comprueba —que ninguna RPC interna sea ejecutable por `anon`— es el bloque 18.',
  '0032': 'solo `comment on table`. No hay garantía que comprobar: lo que fija —que nadie lea `politica_gasto`— se prueba en `politica_un_origen.test.ts`, que sí puede mirar el código.',
  '0197': 'solo `comment on table` (corrige LFPDPPP art. 32→31 en el comentario de `solicitud_arco`, ver 0053). Mismo caso que la 0032: no hay garantía de unicidad/atomicidad/permisos que romper — es documentación visible por `\\d+`, sin efecto en RLS ni en la app.',
  '0038': 'creaba `foto_pendiente`, revertida por la 0041 (AUDITORÍA 9, CRÍTICO: fusionaba comprobantes distintos). El bloque 21 que la comprobaba se retiró junto con la tabla — no queda nada que verificar.',
  '0041': '`drop table foto_pendiente`. Reversión de la 0038; no hay garantía nueva que comprobar, la ausencia de la tabla la confirma cualquier consulta a `information_schema` y no vale la pena un bloque para eso.',
  '0044': 'extiende el dominio de app_user_rol_dominio con un valor más (encargado). La garantía de que basura sigue rechazada ya la prueba el bloque 11 (0025); que "encargado" se acepta se prueba en TS (provisionar.test.ts).',
  '0045': 'RLS de viaje/gasto/liquidacion para el chofer ("el chofer solo ve sus propios viajes"). Su bloque (antes 26) impersonaba un app_user con rol `operador` — retirado el 15-ago-2026 con el MISMO criterio que 0078/0079/0081: la 0086 quitó `operador` del dominio de `app_user.rol`, así que esa sesión ya no puede existir y el INSERT que la armaba rebota contra `app_user_rol_dominio` antes de llegar a nada que probar (lo confirmó la primera corrida automática de verificaciones.sql en CI, 15-ago-2026 — el bloque llevaba desde el 7-ago sin re-verificarse). La garantía que reemplaza a "no ve lo ajeno" es más fuerte, "no puede tener sesión", y la prueba el bloque 62 (0086) — que sigue vivo y corre en la misma batería.',
  '0047': 'RLS de unidad/mantenimiento/incidencia/pod para el chofer. Mismo caso exacto que 0045: su bloque (antes 28) impersonaba `operador`, se retiró el 15-ago-2026 por la misma razón, y queda cubierto por el bloque 62 (0086) — "no puede tener sesión" implica, por construcción, que tampoco pueda leer estas cuatro tablas ni el `pod` ajeno.',
  '0078': 'RLS de las escrituras/lecturas del chofer sobre operador/terminal/política/wa/llm/cfdi. Retirada por la 0086 (operador ya no tiene login): su bloque (antes 54) se borró de verificaciones.sql porque probaba una sesión que ya no puede existir — el bloque 62 (0086) prueba la garantía más fuerte que la reemplaza, "no puede tener sesión".',
  '0079': 'RLS de app_user/bitacora_auditoria para el chofer. Mismo caso que 0078: retirada por la 0086, su bloque (antes 55) se borró por la misma razón — probaba un INSERT de sesión de chofer que hoy rebota en el constraint antes de llegar a RLS.',
  '0081': 'RLS de escritura del POD del chofer, scoped a su propio tenant. Mismo caso: retirada por la 0086, su bloque (antes 56) se borró — no hay sesión de chofer que pueda intentar el POD cruzado que probaba.',
  '0113': 'solo `alter function config_tenant_valida ... set search_path`, mismo caso que la 0035 (bloque 18 la cubre: comprobó que sea SECURITY INVOKER, no hay escalada). La 0085 había regresado el search_path al reescribir la función con CREATE OR REPLACE sin repetir el SET — esta migración solo lo vuelve a fijar, no cambia el cuerpo ni la garantía que ya cubre el bloque 18.',
  '0115': 'extiende el dominio de `agente_corrida_disparo_dominio` con un valor más (whatsapp), mismo caso que la 0044: que basura sigue rechazada ya lo prueba el bloque 86 (0108, que recreó el mismo constraint); que `whatsapp` se acepta se prueba en TS (tools_apagado.test.ts, la corrida del cierre).',
  '0125': 'catálogo declarativo puro: una columna modelo_rol con CHECK de dominio (que basura rebota lo prueba el patrón de CHECKs ya verificado; que los valores se aceptan lo prueba la siembra misma al aplicarse) y ~37 filas nuevas de agente_definicion en estado disenado — el patrón un-agente-es-una-FILA cuya FK/deny-all ya verifica el bloque 91 de la 0116. Sin garantía nueva de unicidad/atomicidad/permisos.',
  '0311': 'recrea `agente_definicion_modelo_rol_dominio` (mismo constraint de la 0125) con la lista COMPLETA de ModelRole, mismo caso que la 0044/0115/0122: que basura sigue rechazada lo prueba el patrón de CHECKs (23514 ruidoso, no corrupción silenciosa — el mismo constraint recreado, sin cambiar de forma); que la lista nueva SÍ empata con ModelRole en las dos direcciones lo prueba TS (agente_definicion_modelo_rol_dominio.test.ts, DATOS-B1), que lee la última definición del CHECK y la cruza contra el tipo — exactamente el arnés que costos_dominio.test.ts ya usa para FaseCosto. Nadie escribe modelo_rol desde la app hoy (darDeAltaAgente no lo incluye), así que no hay unicidad/atomicidad/permiso nuevo que solo Postgres pueda demostrar.',
  '0122': 'dos altas declarativas sin garantía nueva de base: la FILA del redactor en agente_definicion (el patrón FK-como-catálogo ya lo verifica el bloque 91 de la 0116) y la extensión del dominio del CHECK de interruptor — mismo caso que la 0044/0115: que basura sigue rechazada lo prueba el CHECK recreado (bloque de la 0110), y que agente:redactor se acepta se prueba en TS (redactor.test.ts: el kill switch frena al agente).',
  // La 0141 tenía aquí una segunda entrada, escrita por la pasada del 21-ago
  // cuando las columnas GENERADAS de la 0140/0142/0143 iban a tener bloque
  // propio (el 111). Al mergear `master` (22-ago) el 111 pasó a ser la RLS de
  // `liquidacion` (0144) y las tres columnas quedaron EXENTAS con razón escrita
  // arriba. La entrada duplicada se retiró: decía un número de bloque falso, y
  // TypeScript la rechazaba (TS1117).

  '0118': 'tabla `prospecto_contacto` con FKs y CHECKs de dominio que rebotan RUIDOSO (23514/23503, no corrupción silenciosa) y deny-all idéntico al de sus hermanas 0116/0117, cuyo patrón ya verifican los bloques 91-92. La garantía de USO (la cadencia no se duplica: consultar el historial antes de contactar) es de código, y se prueba en TS (cola.test.ts: marcarEnviada registra el contacto).',
  '0168': 'columnas nullable `litros`/`clave_prod_serv` en `cfdi_consolidado_linea` (Fase 1 de docs/asistencia/PLAN-FASES.md — los litros del ECC12 que se leían y se tiraban al persistir). Aditivas, sin CHECK ni garantía de unicidad/atomicidad que solo la base pueda demostrar: si faltan, el `upsert` de consolidado.ts falla ruidoso (columna inexistente), no corrompe en silencio. La decisión de qué línea es diésel y qué clave le corresponde (`claveProdServDeLinea`, concepto_base nativo vs ecc12 TipoCombustible="Diesel"→15101505) y su propagación a `gasto.ocr_extra.litros`/`gasto.clave_prod_serv` (`ligarLineaAGasto`) se prueban en TS contra un ECC12 real (cfdi_xml.test.ts, consolidado.test.ts — describe "FASE 1").',
  '0172': 'recrea el CHECK `tenant_regimen_fiscal_dominio` con 624 Coordinados (c_RegimenFiscal, RFA 2.9). Que basura sigue rechazada lo prueba el patrón de CHECKs ya verificado; que 624 se acepta se prueba en TS (`fiscal.test.ts`: REGIMENES incluye 624 y guardarDatosFiscales lo persiste). Sin unicidad/atomicidad nueva. 0170/0171 ya estaban en master.',
  '0186': 'runtime de agentes: la unicidad de `(tenant_id, effect_key)`, RLS deny-all y los grants service_role, junto con los RPCs de reserva/liquidación, tienen contrato SQL estático cubierto por `src/lib/llm/migration_0186.test.ts`; la carrera real se ejecuta en Postgres dentro de la RPC.',
  '0187': 'leases/fencing de WhatsApp: la migración añade fencing al inbox y a la idempotencia downstream, RPCs server-only con FOR UPDATE SKIP LOCKED, renovación y complete/fail condicionados al token. El contrato SQL y las carreras observables están en `supabase/tests/wa_leases_fencing.sql` y el contrato de adaptadores en `src/lib/likida/wa_pendientes_leases.test.ts`; la carrera de dos sesiones se ejecuta en Postgres local/CI.',
  '0189': 'ensancha el retorno de `finalizar_wa_outbox` de `boolean` a `table(ok, muerta)` — la condición `intentos >= 8` que decide `estado=\'dead\'` es la MISMA de la 0180, sin tocar; no hay unicidad/atomicidad/permiso nuevo que la base sea la única en demostrar. Lo que cambia es el contrato de lectura para la app, y eso se prueba en TS: `wa_outbox.test.ts` fija la forma de fila que PostgREST devuelve (incluidos data=null y data=[] sin reventar en `muerta: true` por accidente), y `cron/wa-outbox/muerta_avisa.test.ts` prueba que el cron avisa exactamente cuando `muerta` es true y no en cualquier fallo transitorio.',
  '0190': 'redefine `sumar_combustible_ejercicio` (misma firma que la 0084/0112) cambiando SOLO qué cuenta como numerador del 15%: de `forma_pago = \'01\'` a la lista cerrada que la LISR 27-III admite por exclusión, igual que `medioNoAdmitidoCombustible` en TS (engine.ts). No crea unicidad/atomicidad/permiso nuevo — es la MISMA agregación de la 0112, con un `filter` distinto. Que las dos cifras (SQL y TS) sigan siendo la misma lo fija `repo_acumulado.test.ts` (equivalencia JS-vs-RPC con vales/dinero electrónico/dación en pago/compensación/novación, y el caso 99=no-pagado que NO cuenta) — un desalineamiento entre esta lista y `MEDIOS_LISR_27_III` fallaría ruidoso ahí antes que en producción. Sustituida por la 0305, que redefine la MISMA función (ver esa entrada).',
  '0305': 'AUDITORÍA 25, FIS-C1/FIS-C2 (CRÍTICO): redefine `sumar_combustible_ejercicio` (misma firma que la 0084/0112/0190) cambiando SOLO qué forma de pago se juzga: de la cruda (`forma_pago`) a la EFECTIVA (`pagado_forma` del REP cuando `forma_pago` es \'99\' y hay `pagado_en`, mig. 0199) — el mismo criterio que `formaPagoJuzgable` (engine.ts:636) y `formaPagoEfectiva` (fiscal.ts). No crea unicidad/atomicidad/permiso nuevo — es la MISMA agregación de la 0190, con la forma de pago derivada en vez de la cruda. Que SQL y TS sigan diciendo la misma cifra lo fija `repo_acumulado.test.ts` (equivalencia JS-vs-RPC, con el caso nuevo: un \'99\' con REP en efectivo SÍ cuenta, uno sin REP no, uno con REP en un medio admitido tampoco) y `fiscal_agregado_15pct.test.ts` (la lista y las dos ramas del `case` fijas contra el `.sql`, línea por línea) — un desalineamiento fallaría ruidoso ahí antes que en producción.',
  '0192': 'redefine `gastos_fiscales_agregados_tenant` (misma firma que la 0151) normalizando `emisor` con `upper(trim(...))` antes de agrupar — sin unicidad/atomicidad/permiso nuevo, es la MISMA agregación de la 0151 con una columna calculada distinta. `fiscal_agregado.test.ts` (equivalencia JS-vs-RPC) fija que "OXXO"/"Oxxo"/" OXXO " se funden en una celda y que un emisor de verdad distinto no se funde de más.',
  '0194': 'ensancha el retorno de `listar_wa_pendientes` (misma firma que la 0187) agregando SOLO la columna `tipo` (`evento ->> \'type\'`) — el resto del cuerpo (filtro, exclusión del anterior vivo, orden, límite) es idéntico byte a byte a la 0187, que ya lo verifica el bloque de leases/fencing. No hay unicidad/atomicidad/permiso nuevo que la base sea la única en demostrar. Lo que cambia es el contrato de lectura para `drenado.ts`, y eso se fija en TS: `wa_pendientes.test.ts` prueba que `pendientesPorDrenar` propaga `tipo` (y cae a `\'other\'` si faltara), y `route.test.ts` (cron) prueba que `hayFotoAntesEnCadena`/`hayFotoDespuesEnCadena` se arman bien a partir de esa columna.',
  '0208': 'columna nullable `viaje.briefing_enviado_en` — el MISMO patrón que la 0087 (recordatorio_comprobacion_en) y que `avisado_en`: la garantía real es que el UPDATE condicional `WHERE briefing_enviado_en IS NULL` es atómico por construcción de Postgres, no una regla que este repo agregue. El sello-tras-envío (lección c2-1: nunca sellar antes de que Meta acepte), la carrera de los dos disparos (despacho + confirmación) y la omisión de secciones sin dato se prueban en TS (briefing_inicio_wa.test.ts). Si la columna falta, el SELECT del briefing falla ruidoso — no corrompe en silencio.',
  '0214': 'dos columnas nullables puras en `viaje` (`ccp_xml_generado_en`/`ccp_xml_generado_por`) — el patrón de la 0208/0087: bitácora de la ÚLTIMA generación del XML de Carta Porte (Fase D export), sin unicidad ni atomicidad nueva que la base sea la única en demostrar (la última generación GANA a propósito — no hay condición WHERE que probar). Quién y cuándo escriben solo desde /api/export/carta-porte-xml tras generar con éxito, y eso —el fail-closed del generador, las puertas de rol y el sello mejor-esfuerzo— se prueba en TS (carta_porte_xml.test.ts y ccp_xml_route.test.ts). La FK a app_user con set null es la forma estándar de la casa para rastros que sobreviven al usuario (0207/0213).',
  '0223': 'un comentario de columna (el dominio de `prospecto.fuente` gana \'landing\' — el contrato vive en la unión de crearProspecto y ahí lo fija vendedores.test) y la tabla `sitio_evento`, un conteo append-only sin datos personales, sin FK de tenant (el sitio público no tiene tenant) y sin unicidad ni atomicidad que la base sea la única en demostrar. Que la tabla tenga RLS activo y cero grants a anon/authenticated lo asevera GLOBALMENTE la capa 1 de la batería (capa1_auditoria_estatica.sql barre el catálogo entero buscando tablas sin RLS y grants de más) — un bloque dedicado repetiría esa aserción. El dominio de `evento` es un CHECK trivial y el único escritor (la API de marketing, con límite de tasa y lista cerrada de páginas) se prueba en TS (marketing_evento_route.test.ts).',
  '0251': 'el hermano interno de la 0223, con su misma razón: `producto_evento` es un conteo append-only sin datos del usuario, sin unicidad ni atomicidad que la base sea la única en demostrar. RLS activo y cero grants a anon/authenticated los asevera GLOBALMENTE la capa 1 (barre el catálogo entero); el `search_path` de las dos funciones nuevas (embudo_activacion, uso_producto_mensual) lo barre el bloque E de esa misma capa sobre TODAS las funciones de public. Los CHECK (dominio de `accion`, forma de `pantalla`) rebotan ruidoso en el INSERT — mismo criterio que la 0137: no se corrompen en silencio. El único escritor (sesión + límite de tasa + catálogo cerrado de pantallas) se prueba en TS (dashboard_evento_route.test.ts), y que las funciones existan lo exige MIGRACIONES_EXIGIDAS/auditor_codigo contra el catálogo real.',
  '0276': 'columna prospecto.empleados + check, EXACTAMENTE la misma forma que la 0137 (unidades): sin unicidad/atomicidad que la base sea la única en demostrar. Si la columna falta, /api/lead lo detecta por el mensaje del insert y salva el lead en `notas` — la red de seguridad de la 0137 se generalizó para cubrirla (api/lead/route.test.ts). El CHECK de dominio rebota ruidoso en el INSERT, no se corrompe en silencio. (Renumerada de 0275 a 0276: colisión con la migración de la ronda de auditoría 23, arco_search_path, mergeada en paralelo con el mismo número.)',
};

const migraciones = readdirSync(DIR)
  .filter((f) => f.endsWith('.sql'))
  .map((f) => ({ num: f.slice(0, 4), archivo: f }))
  .sort((a, b) => a.num.localeCompare(b.num));

describe('toda migración está comprobada o exenta a propósito', () => {
  it('hay migraciones y hay títulos que leer', () => {
    // Sin estas dos, todo lo de abajo pasaría por vacío: cero migraciones no
    // deja huérfanas, y cero títulos las deja todas — pero el mensaje de fallo
    // apuntaría al sitio equivocado.
    expect(migraciones.length).toBeGreaterThan(25);
    expect(TITULOS.split('\n').length).toBeGreaterThan(10);
  });

  it('ninguna se queda sin decisión', () => {
    const huerfanas = migraciones
      .filter(({ num }) => !EXENTAS[num])
      .filter(({ num }) => !new RegExp(`\\b${num}\\b`).test(TITULOS))
      .map(({ archivo }) => archivo);

    expect(
      huerfanas,
      `estas migraciones no tienen bloque en supabase/verificaciones.sql ni una razón en EXENTAS:\n  ${huerfanas.join('\n  ')}\n\n` +
      'Escribe el bloque, o añade la migración a EXENTAS con la razón. Lo que no vale es dejarla sin decidir: ' +
      'así se coló la 0030, que existe justamente porque un chequeo decía verificar algo que no verificaba.',
    ).toEqual([]);
  });

  it('y ninguna exención sobra', () => {
    // Una exención de una migración que ya no existe es una razón que nadie va a
    // volver a leer y que hace parecer cubierto lo que no está.
    const numeros = new Set(migraciones.map((m) => m.num));
    const fantasmas = Object.keys(EXENTAS).filter((n) => !numeros.has(n));
    expect(fantasmas, `EXENTAS nombra migraciones que ya no existen: ${fantasmas.join(', ')}`).toEqual([]);
  });

  it('una exención sin razón no es una exención', () => {
    const vacias = Object.entries(EXENTAS).filter(([, razon]) => razon.trim().length < 20);
    expect(vacias.map(([n]) => n), 'estas exenciones no explican por qué').toEqual([]);
  });
});
